/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NutritionistRouteImport } from './routes/nutritionist'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyNutritionistRouteImport } from './routes/apply-nutritionist'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionistRoute = NutritionistRouteImport.update({
  id: '/nutritionist',
  path: '/nutritionist',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNutritionistRoute = ApplyNutritionistRouteImport.update({
  id: '/apply-nutritionist',
  path: '/apply-nutritionist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply-nutritionist': typeof ApplyNutritionistRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/nutritionist': typeof NutritionistRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply-nutritionist': typeof ApplyNutritionistRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/nutritionist': typeof NutritionistRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply-nutritionist': typeof ApplyNutritionistRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/nutritionist': typeof NutritionistRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply-nutritionist'
    | '/dashboard'
    | '/login'
    | '/nutritionist'
    | '/reset-password'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply-nutritionist'
    | '/dashboard'
    | '/login'
    | '/nutritionist'
    | '/reset-password'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply-nutritionist'
    | '/dashboard'
    | '/login'
    | '/nutritionist'
    | '/reset-password'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyNutritionistRoute: typeof ApplyNutritionistRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NutritionistRoute: typeof NutritionistRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutritionist': {
      id: '/nutritionist'
      path: '/nutritionist'
      fullPath: '/nutritionist'
      preLoaderRoute: typeof NutritionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-nutritionist': {
      id: '/apply-nutritionist'
      path: '/apply-nutritionist'
      fullPath: '/apply-nutritionist'
      preLoaderRoute: typeof ApplyNutritionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyNutritionistRoute: ApplyNutritionistRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NutritionistRoute: NutritionistRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
